### ISSUE TITLE
Bug avec l'activité 10NE1 (impossible de charger le diapo de cet activité depuis un lien)

### ISSUE THREAD

**Issue by Mr-Electro84** [seb-cogez/mathsmentales#10]
Bonjour,
Avant tout je me présente, je suis Mr Electro84, développeur de l'un des seuls fork de MathsMentales, Maths et Matic projector ( https://mem-projector.ml/ ; https://vapps-line-std.github.io/mem-projector ).

Je reviens vers vous pour signaler un bug que j'ai trouvé sur votre site (et sur mon fork) à propos de l'activité 10NE1, en effet si on démarre une activité avec un lien généré depuis l'activité 10NE1, aucun diaporama ne démarre, et ça renvoie cet erreur dans la console JavaScript : 
https://www.cjoint.com/c/KLwkRFHC0zV

Le procédé de reproduction du bug est ici : 
https://www.udrop.com/file/6cQQ/2021-12-22_11-46-16.mp4 (https://www.udrop.com/6cQQ/2021-12-22_11-46-16.mp4 )

Le bug est présent dans la version GitHub, la version de Production et mon fork, cependant de mon coté, j'ai corrigé temporairement le bug en créant le fichier 10NE1.json a l'URL pointé dans la console JS (plus d'informations ici : https://mem-projector.ml/library/N1/NOTE.txt )

Merci d'avoir lu ce message
Mr Electro84

**Comment by seb-cogez** [comment]
Erreur dans regexp, corrigé.
