### ISSUE TITLE
Bug - Variable à valeur nulle qui casse tout le site

### ISSUE THREAD

**Issue by Mr-Electro84** [seb-cogez/mathsmentales#13]
Bonjour,

Je suis encore ici pour signaler un bug qui fait casser tout le site, le bug concerne : 

- Version GitHub
- Mon fork (Maths et Matic Projector)
- La version de production n'est pas concernée

Le bug fait casser tout le site, impossible de démarrer une diaporama, générer un lien, feuille d'exo...
En cause, très probablement le fait qu'une variable soit nulle à en croire la console JavaScript
![Console JS](https://www.cjoint.com/doc/22_01/LAqsT421RiV_clipimage.jpg)
![Console JS Firefox](https://www.cjoint.com/doc/22_01/LAqs0EJP5LV_clipimage.jpg)

Bien sur ce ne sont que des hypothèses, je ne sais pas si d'autres causes pourrait être à l'origine de ce bug

Testé sur : Google Chrome et Mozilla Firefox

Merci d'avoir lu ce message
Mr_Electro84

**Comment by seb-cogez** [comment]
Bonjour,
La version Github fonctionne bien, tout comme la version de prod qui lui est identique. Votre problème vient de votre cache navigateur qui a gardé un petit bug introduit il y a peu, mais qui a été vite corrigé suite aux remontées qui m'ont été faites le jour même de la mise en prod.
Cdlt

**Comment by Mr-Electro84** [comment]
@seb-cogez  Bonjour,
Désolé de poster un message post fermeture.

J'ai tout essayé : vider les donnés du site, vider le cache, essayer avec un autre navigateur, consulter le site depuis un VPN, télécharger le code source de mathsmentales et l'exécuter en local, consulter le site depuis mon mobile (et en données mobiles)... 
j'ai toujours cette même erreur dans la console JS, et toujours impossible de faire quoi que ce soit.

Et justement, en vidant le cache et les données pour mon fork sur plusieurs navigateurs, la situation à empiré puisqu'un navigateur qui n'était pas concerné par le bug vient d'être touché

Je vais attendre encore quelques heures pour voir si le bug est toujours présent. Et je reposterai un message sur cet issue, à l'instant T, j'ai toujours ce bug de mon coté

Merci d'avoir lu ce message
Mr_Electro84

**Comment by Mr-Electro84** [comment]
@seb-cogez Re-bonjour,
J'ai laissé quelques heures, et j'ai revérifié le site pour voir si le bug était toujours présent, avec plusieurs navigateurs (Chrome, Firefox, Edge), avec plusieurs supports (PC sous Windows 11, Téléphone sous Android 11, PC sous Ubuntu 20.04.3 (LTS)), avec plusieurs moyens de connexion (WiFi, Données Mobiles, VPN), et même en vidant le cache ou en supprimant les données j'ai toujours la même erreur dans la console JavaScript : 
![image](https://user-images.githubusercontent.com/79417900/149793061-6eff935d-182c-4788-8892-24f352050646.png)
![image](https://user-images.githubusercontent.com/79417900/149793074-60154812-a04e-4030-944d-ff7d8ca6d89f.png)

Je pense qu'avec les combinaisons possibles que j'ai fait, ce n'est surement pas un problème de cache dans le navigateur.

Merci d'avoir lu ce message
Mr_Electro84

**Comment by seb-cogez** [comment]
C'est réparé. Désolé pour ce désagrément du à mon manque de maitrise de github.
