### ISSUE TITLE
Impossible de générer aléatoirement une clé de données

### ISSUE THREAD

**Issue by Mr-Electro84** [seb-cogez/mathsmentales#18]
Bonjour,

Je viens signaler un bug sur le site

Version de production : Non
Version GitHub : **Oui**

### Procédure à suivre

1. Choisir une activité sur le site (ex : https://seb-cogez.github.io/mathsmentales/?u=10NB1 )
2. Activer la fonction "Clé de données"
3. Cliquez sur le dé

Une clé de données est sensée se régénérer en théorie, en pratique elle ne se régénère pas, voici l'erreur qu'on obtient dans la console : 
Google Chrome
![image](https://user-images.githubusercontent.com/79417900/212163197-f302ee18-0118-45e9-b9da-87d0b192cd17.png)
Slimjet
![image](https://user-images.githubusercontent.com/79417900/212162173-b461bcf7-9807-449b-9ab8-bd5e507c7f06.png)
MS Edge
![image](https://user-images.githubusercontent.com/79417900/212163036-8a76b87d-5165-4b38-8d1a-b9a7a101b12d.png)

Testé sur : Google Chrome, Microsoft Edge et [Slimjet](https://www.slimjet.com/fr/) (fork de Chromium) sur Windows 11

Merci d'avoir lu ce message
Mr_Electro84

**Comment by seb-cogez** [comment]
Problème corrigé.
